### ISSUE TITLE
DELETE /pins/{reference} Fails with 500 Internal Server Error

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#2713]
### Context 
Old bee nodes that have been running both in mainnet and testnet for a long time having supported a large volume of uploads over time.  See also #2712 

### Summary
When trying to use DELETE /pins/{reference} where the references are retrieved with a GET /pins query, many of them are failing with 500 Internal Server Error and the pin is not deleted.

### Expected behavior
If I ask to delete a pin, I would expect it to be deleted.

### Actual behavior
The pin is not deleted and an error is returned.  The --verbosity 5 logs show that the traversal of the specified reference is failing because some secondary chunk below the reference is not found.  Given that the pin exists, one would have hoped that all of the chunks for that reference would also exist, except for #2712 

### Steps to reproduce
Again, difficult to reproduce, but if you can create an existing pin for which not all of the traversal chunks are actually pinned and are now not retrievable from the swarm, then you will be unable to delete that pin due to traversal failure.

### Possible solution
I'm planning to disable the traversal in DeletePin since my pins were all created with /bytes uploads with Swarm-Pin specified which, as #2712 describes, actually only creates the statestore key and doesn't actually pin anything in localstore.  This will hopefully get my nodes cleaned up, but is not a general solution.

**Comment by asabya** [comment]
Facing the same issue on `v1.4.3-1213e063`

I'm calling "POST" on `/bytes` with `pin` and `encrypt` headers `true`. After getting the reference, if I call "DELETE" on `/pins/<encrypted_reference>` I get `"Internal Server Error"` with `500`

The file size is  ~190kb

logs
```
DEBU[2022-03-11T17:39:32+05:30] unpin root hash: deletion of pin for "68fd6487cbaf2a08d9436256646359319a02d25c8fcd46604a654813384b25b808fbe2398155b0b3aae32b4c425e513a6c96bd74f35a008482f41a3e93dbf711" failed: 3 errors occurred:
	* traversal iteration failed
	* get value: leveldb: not found
	* unable to unpin the chunk for leaf "5258edfebc646b8beeca62bc0778f09a73254c7c7494624dd340ba0fe1875119393b094b34b0803b1c63be37b99aa19ac7475f0060cb49e97b2635986e5165fe" of root "68fd6487cbaf2a08d9436256646359319a02d25c8fcd46604a654813384b25b808fbe2398155b0b3aae32b4c425e513a6c96bd74f35a008482f41a3e93dbf711": get value: leveldb: not found
```

**Comment by tfius** [comment]
is there any progress on this ?

**Comment by acud** [comment]
I can reproduce the problem (and fix it) for encrypted content, but unfortunately I cannot for unencrypted content. @asabya afaik fds encrypts everything so I assume this can and will be fixed, however @ldeffenb your original bug report did not mention encryption. If the content was not encrypted, the only reason unpinning could fail would be because some of the chunk addresses would be in the push index queue (which is kinda legal behavior but also screws up the consistency of the unpinned collection, since some chunks may be unpinned multiple times if you try to unpin it again in the future, and some of the dangling entries that were already unpinned may be removed since they end up in the cache and may be evicted. This might be the reason for the "chunk-rot" you've been talking about).

**Comment by ldeffenb** [comment]
@acud You are correct in your assumption that my content is not encrypted.  I upload it directly and count on the de-duplication of the swarm to only store single copies of duplicate data.

**Comment by acud** [comment]
@ldeffenb I marked this as `wontfix` since I cannot reproduce this. We fixed a bug related to this with unpinning of encrypted chunks but I cannot reproduce the problem you've described. Leaving this open so we can collect more information about this.

**Comment by asabya** [comment]
@acud It seems the issue still persists with bee `1.6.0-rc2-6ce1d595` 

```
DEBU[2022-05-09T11:19:27+05:30] unpin root hash: deletion of pin for "213d6f3be9af736f6e83972d265ee6e5f648f142b7f35f4f2b6f4fab58b06883" failed: traversal of "213d6f3be9af736f6e83972d265ee6e5f648f142b7f35f4f2b6f4fab58b06883" failed: 1 error occurred:
	* traversal: unable to process bytes for "213d6f3be9af736f6e83972d265ee6e5f648f142b7f35f4f2b6f4fab58b06883": manifest iterate addresses: storage: not found
 
ERRO[2022-05-09T11:19:27+05:30] unpin root hash: deletion of pin for failed  
INFO[2022-05-09T11:19:27+05:30] api access                                    duration=8.286962917 ip="::1" method=DELETE proto=HTTP/1.1 size=72 status=500 uri=/pins/213d6f3be9af736f6e83972d265ee6e5f648f142b7f35f4f2b6f4fab58b06883 user-agent=Go-http-client/1.1
```

**Comment by crtahlin** [comment]
@asabya please check if problem still exists and if you can provide info to reproduce the issue, provide it and reopen issue.

**Comment by asabya** [comment]
I can confirm this is not happening for Bytes in the latest version.

**Comment by asabya** [comment]
I still face this for SOC though
```
INFO[2022-05-26T17:05:30+05:30] api access                                    duration=0.007136667 ip="::1" method=POST proto=HTTP/1.1 size=94 status=201 uri="/soc/ef552ff649ebca68c37ddc28e25a27a55657c916/e1987b7e93640469a116a2327de50599afc2c977935ddd189259b540753b65e2?sig=8843051fefa23a4f6fca446ce7e66b730731119f52753bc7a13c8ad6717cbd244bad9280f41ca179b5b07b336f1e7a5a0f59c3b7340c14afe16a35ebef2630741c" user-agent=Go-http-client/1.1
DEBU[2022-05-26T17:05:38+05:30] batchstore: put chain state block 6951875 amount 2018639 price 1 
DEBU[2022-05-26T17:05:38+05:30] batch service: updated block height to 6951875 
DEBU[2022-05-26T17:05:55+05:30] retrieval: failed to get chunk a116a2327de50599afc2c977935ddd189259b540753b65e28843051fefa23a4f from peer d61a7f67dbff82035a4414f65d1d17803f0fc5634d76cb59be4c6f38eab0faf1: read delivery: stream reset peer d61a7f67dbff82035a4414f65d1d17803f0fc5634d76cb59be4c6f38eab0faf1 
DEBU[2022-05-26T17:05:55+05:30] retrieval: failed to get chunk a116a2327de50599afc2c977935ddd189259b540753b65e28843051fefa23a4f from peer ba545fce30e7ef9d2a1c0e4ab270795182eb2a89facbcccd4bba8001d2c4eaba: read delivery: stream reset peer ba545fce30e7ef9d2a1c0e4ab270795182eb2a89facbcccd4bba8001d2c4eaba 
DEBU[2022-05-26T17:05:55+05:30] retrieval: failed to get chunk a116a2327de50599afc2c977935ddd189259b540753b65e28843051fefa23a4f from peer 9179619fe45a0fa285eaab74c04353937bc641110a02489a1689b6f62c52cdf4: read delivery: stream reset peer 9179619fe45a0fa285eaab74c04353937bc641110a02489a1689b6f62c52cdf4 
DEBU[2022-05-26T17:05:55+05:30] retrieval: failed to get chunk a116a2327de50599afc2c977935ddd189259b540753b65e28843051fefa23a4f from peer 9b7e389cb940964263fdd8c7abce245f3ec36d19c369c08afa532de8761fbbce: read delivery: stream reset peer 9b7e389cb940964263fdd8c7abce245f3ec36d19c369c08afa532de8761fbbce 
DEBU[2022-05-26T17:05:55+05:30] retrieval: failed to get chunk a116a2327de50599afc2c977935ddd189259b540753b65e28843051fefa23a4f from peer f320fb810fe20dc35777814750a428e67443202f80521951b4bd64f995c23728: read delivery: stream reset peer f320fb810fe20dc35777814750a428e67443202f80521951b4bd64f995c23728 
DEBU[2022-05-26T17:05:55+05:30] retrieval: failed to get chunk a116a2327de50599afc2c977935ddd189259b540753b65e28843051fefa23a4f from peer ae9dc64be8bb95fa900094f2c4ee7f06947155efe0d9981ff06866319cc20910: read delivery: stream reset peer ae9dc64be8bb95fa900094f2c4ee7f06947155efe0d9981ff06866319cc20910 
DEBU[2022-05-26T17:05:55+05:30] retrieval: failed to get chunk a116a2327de50599afc2c977935ddd189259b540753b65e28843051fefa23a4f from peer 810180d4cdc5866e33ff82763b4761352e9f3692ccaf7740f43353810575b228: read delivery: stream reset peer 810180d4cdc5866e33ff82763b4761352e9f3692ccaf7740f43353810575b228 
DEBU[2022-05-26T17:05:55+05:30] retrieval: failed to get chunk a116a2327de50599afc2c977935ddd189259b540753b65e28843051fefa23a4f from peer b7563e7412aafac997a2b165aedfc1648eb70b6360a73fc425f8db9a3b136510: read delivery: stream reset peer b7563e7412aafac997a2b165aedfc1648eb70b6360a73fc425f8db9a3b136510 
DEBU[2022-05-26T17:05:55+05:30] unpin root hash: deletion of pin for "bd760322e2d9c86bf7346f1ca319315cc81e69584f77d30a449beee3c5b39fee" failed: traversal of "bd760322e2d9c86bf7346f1ca319315cc81e69584f77d30a449beee3c5b39fee" failed: 1 error occurred:
	* traversal: unable to process bytes for "bd760322e2d9c86bf7346f1ca319315cc81e69584f77d30a449beee3c5b39fee": manifest iterate addresses: storage: not found
 
ERRO[2022-05-26T17:05:55+05:30] unpin root hash: deletion of pin for failed  
INFO[2022-05-26T17:05:55+05:30] api access                                    duration=8.29183775 ip="::1" method=DELETE proto=HTTP/1.1 size=72 status=500 uri=/v1/pins/bd760322e2d9c86bf7346f1ca319315cc81e69584f77d30a449beee3c5b39fee user-agent=PostmanRuntime/7.29.0
```

**Comment by agazso** [comment]
What do you mean for SOC? Can you please describe the steps you are doing to reproduce this?

**Comment by asabya** [comment]
1. I upload an SOC
- POST on `http://localhost:1633/soc/ef552ff649ebca68c37ddc28e25a27a55657c916/e1987b7e93640469a116a2327de50599afc2c977935ddd189259b540753b65e2?sig=8843051fefa23a4f6fca446ce7e66b730731119f52753bc7a13c8ad6717cbd244bad9280f41ca179b5b07b336f1e7a5a0f59c3b7340c14afe16a35ebef2630741c
` with `swarm-pin` header. this returns the reference `bd760322e2d9c86bf7346f1ca319315cc81e69584f77d30a449beee3c5b39fee`
2. Now if I call `http://localhost:1633/pins/bd760322e2d9c86bf7346f1ca319315cc81e69584f77d30a449beee3c5b39fee` I get 
```
{
    "message": "Internal Server Error",
    "code": 500
}
``` 
with the above log
